### ISSUE TITLE
IntraACL ruins SpecialPages(Disambiguations, DoubleRedirects, BrokenRedirects)

### ISSUE THREAD

**Issue by dsnopkiewicz** [mediawiki4intranet/IntraACL#36] opened 2015-03-05 08:28 UTC
platform : Mediawiki = 1.19.14 IntraACL = 2.1.4
IntraAcl in QueryPage.php makes Mysql ERROR 1052 (23000): Column 'page_namespace' in field list is ambiguous
on Special Pages: Disambiguations, DoubleRedirects, BrokenRedirects

**Comment by vitalif** [comment] 2015-03-05 12:34
Hm... I can't reproduce this problem. Can you set $wgShowSQLErrors = true and post the buggy sql query?

**Comment by dsnopkiewicz** [comment] 2015-03-06 05:44
A database query syntax error has occurred. This may indicate a bug in the software. The last attempted database query was:

    SELECT pa.page_namespace AS namespace,pa.page_title AS title,pa.page_title AS value,pb.page_namespace AS nsb,pb.page_title AS tb,pc.page_namespace AS nsc,pc.page_title AS tc,page_namespace,page_title FROM `redirect` `ra`,`redirect` `rb`,`page` `pa`,`page` `pb`,`page` `pc` WHERE (ra.rd_from = pa.page_id) AND (pb.page_namespace = ra.rd_namespace) AND (pb.page_title = ra.rd_title) AND (rb.rd_from = pb.page_id) AND (pc.page_namespace = rb.rd_namespace) AND (pc.page_title = rb.rd_title) ORDER BY ra.rd_namespace, ra.rd_title LIMIT 50 

from within function "DoubleRedirectsPage::reallyDoQuery". Database returned error "1052: Column 'page_namespace' in field list is ambiguous (localhost)".

**Comment by jaceklaskowski** [comment] 2015-03-24 23:49
I'm working with @dsnopkiewicz to help resolving the issue. The screenshot attach to show the issue as it surfaces in our instance.

![mediawiki-database-error-issue](https://cloud.githubusercontent.com/assets/62313/6815288/2bbe631c-d288-11e4-8954-934203c5539a.png)

Does this help hunting down the issue? What else would be helpful to offer a solution?

**Comment by jaceklaskowski** [comment] 2015-03-25 00:04
It turns out that `page_namespace` column name really appears four times in the SELECT clause and the last one (just before `FROM`) doesn't have a table alias (`pa`, `pb`, `pc`) that leads to the issue.

**Comment by jaceklaskowski** [comment] 2015-03-25 00:15
Further investigation revealed that the page `QueryPage.php` is indeed patched during the installation of IntraACL in https://github.com/mediawiki4intranet/IntraACL/blob/master/patches/IntraACL-MediaWiki-1.19.16.diff#L195-L224 (we're using MediaWiki 1.19.14) that seem to introduce the bug as the column names are not aliased (see https://github.com/mediawiki4intranet/IntraACL/blob/master/patches/IntraACL-MediaWiki-1.23.2.diff#L193-L194).

**Comment by vitalif** [comment] 2015-03-25 10:20
Thanks, it seems I've tried to reproduce this issue in 1.21, but it's specific only for MW 1.19. Fixed it with the latest commit.

**Closed** 2015-03-25 10:19 UTC
